apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: ALLOWED_ORIGINS
              value: "https://cloudnetbiz.com"
